export default {
  CREATE: 'TOPBAR_BUTTON_CREATE',
  MENU: 'TOPBAR_BUTTON_MENU',
  BACK: 'TOPBAR_BUTTON_BACK',
  FILTER: 'TOPBAR_BUTTON_FILTER',
  SEARCH: 'TOPBAR_BUTTON_SEARCH',
  CREATE_TEXT_BUTTON: 'TOPBAR_CREATE_TEXT_BUTTON',
};
