const API_ROUTE = '/api/v1';
const API_ROUTE_PORTAL = `${API_ROUTE}/portal`;
const API_ROUTE_CATALOG = `${API_ROUTE}/users/catalog`;

export default {
  login: '/api/v1/auth/login',
  tokenRefresh: '/api/v1/auth/refresh',
  logout: '/api/v1/auth/logout',
  userInfo: '/api/v1/auth/me',
  profile: '/api/v1/profile',
  visitsStatistic: '/api/v1/statistic/visit',
  catalogEmployees: '/api/v1/users/catalog',
  approvalsCabinet: '/api/v1/tasks/approval',
  news: '/api/v1/news',
  info: '/api/v1/info',
  approvalsCabinetDownload: '/api/v1/tasks/approval/download',
  approvalsCabinetDownloadTypeYX: `${API_ROUTE}/tasks/approval/download/accountant`,
  kipFileDownload: '/api/v1/portal/kip/file',
  activeSessions: '/api/v1/auth/session/list',
  activeSessionDelete: '/api/v1/auth/session/delete',
  activeSessionsClear: '/api/v1/auth/session/clear',
  badges: '/api/v1/badges',
  pass_requests: '/api/v1/request/pass',
  pass_requests_create: '/api/v1/request/pass/create',
  offices_list: '/api/v1/information/offices',
  support_requests: '/api/v1/request/support',
  documents_requests: `${API_ROUTE_PORTAL}/documents`,
  document_requests_info: id => `${API_ROUTE_PORTAL}/document/${id}`,
  tasks: '/api/v1/portal/kip',
  diary: '/api/v1/portal/employee/tasks',
  taskCreate: '/api/v1/portal/kip/create',
  taskChangeStatus: taskId => `/api/v1/portal/kip/${taskId}/update/status`,
  taskAddComment: taskId => `/api/v1/portal/kip/${taskId}/comment`,
  taskAddAttachment: `${API_ROUTE_PORTAL}/kip/file`,
  tableReports: '/api/v1/tableau',
  delegations: '/api/v1/delegations',
  payrollDownload: '/api/v1/profile/payroll',
  vacations: '/api/v1/portal/vacations',
  vacationsLimit: `${API_ROUTE_PORTAL}/vacations/limit`,
  vacationsByType: type => `/api/v1/portal/vacations/type/${type}`,
  vacationEdit: id => `${API_ROUTE_PORTAL}/vacations/${id}`,
  subscriptionCheck: idPhPerson =>
    `${API_ROUTE_CATALOG}/${idPhPerson}/subscribe_check`,
  subscriptionSubscribe: idPhPerson =>
    `${API_ROUTE_CATALOG}/${idPhPerson}/subscribe`,
  subscriptionUnsubscribe: idPhPerson =>
    `${API_ROUTE_CATALOG}/${idPhPerson}/unsubscribe`,
  settingsNotifications: `${API_ROUTE}/notifications`,
  settingsNotificationsSave: `${API_ROUTE}/notifications`,
  document_requests_create: `${API_ROUTE_PORTAL}/documents/create`,
  inquiriesList: type => `${API_ROUTE_PORTAL}/inquiry/${type}`,
  inquiryData: (type, id) => `${API_ROUTE_PORTAL}/inquiry/${type}?id=${id}`,
  inquiryCreate: type => `${API_ROUTE_PORTAL}/inquiry/${type}`,
};
